version: '3.0'
services:
  mysql8:
    image: mysql:8.0.29
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      #初始化脚本
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      # 端口映射
      - "13306:3306"
  redis:
    image: 'redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '16379:6379'
  etcd:
    image: 'bitnami/etcd'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - '12379:2379'
  mongo:
    image: 'mongo:6.0'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

  prometheus:
    image: 'prom/prometheus:v2.47.2'
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana-enterprise:10.2.0
    ports:
      - 3000:3000


